In [3]:
from layers import Linear
import numpy as np
X = np.random.randn(3,2) 
Weight = np.random.randn(2,5)*0.01
bias = np.zeros((1,5))

linear = Linear(in_dims = 2 ,neurons_num =  5) 
linear.W = Weight
linear.b = bias
Z = linear.forward(X) 
dZ = np.ones_like(Z)
print(Z.shape) 
dX = linear.backward(dZ)
print("shape của dX và X bằng nhau là: ", dX.shape == X.shape)
print("shape của db và b bằng nhau là: ", linear.db.shape == bias.shape)
print("shape của dW và W bằng nhau là: ", linear.dW.shape == Weight.shape)



(3, 5)
shape của dX và X bằng nhau là:  True
shape của db và b bằng nhau là:  True
shape của dW và W bằng nhau là:  True


In [2]:
import numpy as np
Z = np.random.randint(-1, 2, size=(3, 3))

from activations import ReLU
#check shape dA(cùng shape với Z)
Activation = ReLU()
print("mask: ",Activation.forward(Z), " " , "Z :" ,Z )
dA = np.ones_like(Z)
print("shape của dA và Z bằng nhau là: " , Activation.backward(dA).shape == Z.shape)

mask:  [[0 1 0]
 [1 0 0]
 [1 1 1]]   Z : [[-1  1  0]
 [ 1  0 -1]
 [ 1  1  1]]
shape của dA và Z bằng nhau là:  True
